version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  openclojure:
    lang: dockerfile
    handler: ./openclojure
    image: openclojure:1.5
    limits:
          memory: 1000Mi
          cpu: 1000m
        requests:
          memory: 1000Mi
          cpu: 1000m