version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  openclojure:
    lang: dockerfile
    handler: ./openclojure
    image: openclojure:latest
    resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
    environment:
        read_timeout: 60s
        write_timeout: 60s
    annotations:
     com.openfaas.health.http.initialDelay: "60s"

